server:
  port: 10001
spring:
  application:
    name: easyexcel
  #      Spring Cloud Netflix Ribbon现在处于维护模式，因此我们建议改用Spring Cloud LoadBalancer
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: hankun
    password: Hankun0421.
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.43.148.85:3306/wf?serverTimezone=CTT


eureka:
  client:
    service-url:
#      defaultZone: http://182.43.148.85:8761/eureka/
      defaultZone: http://10.0.31.34:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000