server:
  port: 10001
spring:
  application:
    name: easyexcel
  #      Spring Cloud Netflix Ribbon现在处于维护模式，因此我们建议改用Spring Cloud LoadBalancer
  cloud:
    loadbalancer:
      ribbon:
        enabled: false


eureka:
  client:
    service-url:
      defaultZone: http://182.43.148.85:8761/eureka/
#      defaultZone: http://10.0.31.34:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000